name: Nightly Canvas Export (Students)

on:
  workflow_dispatch:
  schedule:
    # offset from Courses job
    - cron: "30 5 * * *"

permissions:
  contents: read

jobs:
  run-export-students:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - key: B2C_P1
            table: "B2C Student Enrollments"
            soft_delete: "false"
          - key: B2C_P2
            table: "B2C Student Enrollments"
            soft_delete: "false"

          - key: SOUTHLANDS
            table: "Southlands Student Enrollments"
            soft_delete: "true"
          - key: PHOENIX
            table: "Phoenix Christian Student Enrollments"
            soft_delete: "true"
          - key: ONE_TWO_ONE_ONE
            table: "1211 Student Enrollments"
            soft_delete: "true"
          - key: NHCC
            table: "NHCC Student Enrollments"
            soft_delete: "true"
          - key: ROCKCHRISTIAN
            table: "Rock Christian Student Enrollments"
            soft_delete: "true"
          - key: GANEVAS
            table: "Ganevas Student Enrollments"
            soft_delete: "true"

          # --- New cohorts you requested (with soft-delete) ---
          - key: NHCC_GLENDALE
            table: "NHCC Journey (Glendale) Student Enrollments"
            soft_delete: "true"
          - key: NHCC_IRONWOOD
            table: "NHCC Ironwood (Casa Grande) Student Enrollments"
            soft_delete: "true"
          - key: NHCC_CENTRAL
            table: "NHCC Central (Tempe) Student Enrollments"
            soft_delete: "true"
          - key: NHCC_CHANDLER
            table: "NHCC Grace (Chandler) Student Enrollments"
            soft_delete: "true"
          - key: EARL_FRANKLIN
            table: "Earl Franklin Student Enrollments"
            soft_delete: "true"
          - key: ODISEA_SPORTS
            table: "Odisea Sports Management Student Enrollments"
            soft_delete: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Resolve Canvas IDs for cohort
        id: resolve_ids
        shell: bash
        env:
          INCLUDE_CANVAS_IDS_P1: ${{ secrets.INCLUDE_CANVAS_IDS_P1 }}
          INCLUDE_CANVAS_IDS_P2: ${{ secrets.INCLUDE_CANVAS_IDS_P2 }}
          IDS_SOUTHLANDS:        ${{ secrets.IDS_SOUTHLANDS }}
          IDS_PHOENIX:           ${{ secrets.IDS_PHOENIX }}
          IDS_1211:              ${{ secrets.IDS_1211 }}
          IDS_ROCKCHRISTIAN:     ${{ secrets.IDS_ROCKCHRISTIAN }}
          IDS_GANEVAS:           ${{ secrets.IDS_GANEVAS }}
          IDS_NHCC:              ${{ secrets.IDS_NHCC }}
          # --- New secret variables ---
          IDS_NHCC_GLENDALE:             ${{ secrets.IDS_NHCC_GLENDALE }}
          IDS_NHCC_IRONWOOD:             ${{ secrets.IDS_NHCC_IRONWOOD }}
          IDS_NHCC_CENTRAL:              ${{ secrets.IDS_NHCC_CENTRAL }}
          IDS_NHCC_CHANDLER:             ${{ secrets.IDS_NHCC_CHANDLER }}
          IDS_EARL_FRANKLIN:             ${{ secrets.IDS_EARL_FRANKLIN }}
          IDS_ODISEA_SPORTS_MANAGEMENT:  ${{ secrets.IDS_ODISEA_SPORTS_MANAGEMENT }}
        run: |
          case "${{ matrix.key }}" in
            B2C_P1)          echo "ids=$INCLUDE_CANVAS_IDS_P1" >> $GITHUB_OUTPUT ;;
            B2C_P2)          echo "ids=$INCLUDE_CANVAS_IDS_P2" >> $GITHUB_OUTPUT ;;
            SOUTHLANDS)      echo "ids=$IDS_SOUTHLANDS"        >> $GITHUB_OUTPUT ;;
            PHOENIX)         echo "ids=$IDS_PHOENIX"           >> $GITHUB_OUTPUT ;;
            ONE_TWO_ONE_ONE) echo "ids=$IDS_1211"              >> $GITHUB_OUTPUT ;;
            ROCKCHRISTIAN)   echo "ids=$IDS_ROCKCHRISTIAN"     >> $GITHUB_OUTPUT ;;
            GANEVAS)         echo "ids=$IDS_GANEVAS"           >> $GITHUB_OUTPUT ;;
            NHCC)            echo "ids=$IDS_NHCC"              >> $GITHUB_OUTPUT ;;
            NHCC_GLENDALE)   echo "ids=$IDS_NHCC_GLENDALE"     >> $GITHUB_OUTPUT ;;
            NHCC_IRONWOOD)   echo "ids=$IDS_NHCC_IRONWOOD"     >> $GITHUB_OUTPUT ;;
            NHCC_CENTRAL)    echo "ids=$IDS_NHCC_CENTRAL"      >> $GITHUB_OUTPUT ;;
            NHCC_CHANDLER)   echo "ids=$IDS_NHCC_CHANDLER"     >> $GITHUB_OUTPUT ;;
            EARL_FRANKLIN)   echo "ids=$IDS_EARL_FRANKLIN"     >> $GITHUB_OUTPUT ;;
            ODISEA_SPORTS)   echo "ids=$IDS_ODISEA_SPORTS_MANAGEMENT" >> $GITHUB_OUTPUT ;;
            *) echo "Unknown cohort key: ${{ matrix.key }}"; exit 1 ;;
          esac

      # ---------- Build per-student-year CSV (with fallback row if no enrollments) ----------
      - name: Build per-student CSV for Airtable (${{ matrix.table }})
        env:
          API_URL: ${{ secrets.CANVAS_API_URL }}
          API_KEY: ${{ secrets.CANVAS_API_KEY }}
          IDS:     ${{ steps.resolve_ids.outputs.ids }}
        run: |
          python - <<'PY'
          # (unchanged) ... your existing Python block ...
          PY

      - name: Preview first 30 lines of CSV
        run: |
          echo "----- Canvas_Enrollments.csv (head) -----"
          head -n 30 Canvas_Enrollments.csv

      - name: Upload CSVs (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: student-csvs-${{ matrix.key }}
          path: "*.csv"

      - name: Upsert Students → Airtable (${{ matrix.table }})
        env:
          AIRTABLE_PAT:        ${{ secrets.AIRTABLE_PAT }}
          AIRTABLE_BASE_ID:    ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_NAME: ${{ matrix.table }}
        run: |
          python - <<'PY'
          # (unchanged) ... your existing Python block ...
          PY

      - name: Ensure current STUDENT rows are Active=true
        env:
          AIRTABLE_PAT:        ${{ secrets.AIRTABLE_PAT }}
          AIRTABLE_BASE_ID:    ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_NAME: ${{ matrix.table }}
        run: |
          python - <<'PY'
          # (unchanged) ... your existing Python block ...
          PY

      - name: Mark missing STUDENT records as inactive (soft-delete)
        if: ${{ matrix.soft_delete != 'false' }}
        env:
          AIRTABLE_PAT:        ${{ secrets.AIRTABLE_PAT }}
          AIRTABLE_BASE_ID:    ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_NAME: ${{ matrix.table }}
        run: |
          python - <<'PY'
          # (unchanged) ... your existing Python block ...
          PY

  # ---------- Union soft-delete for B2C Students across P1/P2 ----------
  softdelete-b2c-students:
    needs: run-export-students
    runs-on: ubuntu-24.04
    steps:
      - name: Download B2C P1 CSV
        uses: actions/download-artifact@v4
        with:
          name: student-csvs-B2C_P1
          path: b2c-p1
      - name: Download B2C P2 CSV
        uses: actions/download-artifact@v4
        with:
          name: student-csvs-B2C_P2
          path: b2c-p2

      - name: Union soft-delete for B2C Students
        env:
          AIRTABLE_PAT:     ${{ secrets.AIRTABLE_PAT }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        run: |
          python - <<'PY'
          # (unchanged) ... your existing Python block ...
          PY
